spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false #关闭模板引擎缓存
  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd #时间日期格式化
mybatis:
  type-aliases-package: com.ls.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
server:
  servlet:
    context-path: /ls #设置项目虚拟目录
  port: 80
